site_name: Django Portal - General User Docs
site_url: https://airavata.apache.org/
site_description: Apache Airavata Django Portal General User Documentation

repo_url: https://github.com/apache/airavata-user-docs

docs_dir: docs

nav:
- Home: 'index.md'
- General:
  - Quick Start: 'user-documentation/quick-start.md'
  - Create User Account: 'user-documentation/account-creation.md'
  - Create Experiment & Launch Job: 'user-documentation/create-experiment-launch-job.md'
  - Monitor Your Experiment: 'user-documentation/monitor-experiment.md'
  - Clone, Cancel and Share: 'user-documentation/clone-cancel-share.md'
  - Create Your Groups: 'user-documentation/create-groups.md'
  - Use Your Own HPC Account: 'user-documentation/personal-allocation.md'
  - Other Features: 'user-documentation/other-features.md'
- Contact Us: 'contact-us.md'

theme: readthedocs

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
     permalink: 
  - admonition
